export const COGNITO_REGION = 'us-east-1'
export const COGNITO_IDENTITY_POOL_REGION = 'us-east-2'
export const COGNITO_IDENTITY_POOL_ID = 'us-east-2:70e2ea2c-2fe3-4f87-a100-76b6fbb90ef9'
export const USER_POOL_ID = 'us-east-2_oarQzF4iu'
export const USER_POOL_CLIENT_ID = 'jehmmgbapfe3fd4566jptl9ct'
